 A-NODE, B-NODE, -C-NODE, ERROR NUMBER, PARAM1, PARAM2, TEXT
         0,     1002,        0,  19,0, 0, Total stage plus intergreen times not equal input cycle time
      7506,     1004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7506,     1004,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     1005,        0, 183,0, 0, LCY for a node differs from its neighbours
      2014,     1005,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2789,     1005,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2789,     1005,        0, 152,0, 0, A single lane arm at signals which includes an X-marked turn
      2013,     1006,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2013,     1006,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2119,     1009,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2119,     1009,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      5003,     1013,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      5003,     1013,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7047,     1013,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7048,     1013,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     1016,        0,  84,0, 0, Redundant intergreen stage time - all turns continuous green
      1019,     1018,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1020,     1018,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2147,     1018,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2147,     1018,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     1020,        0, 183,0, 0, LCY for a node differs from its neighbours
      1018,     1020,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2992,     1020,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2032,     1021,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2032,     1021,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5018,     1021,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      5018,     1021,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1094,     1026,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      1094,     1026,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1212,     1029,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1212,     1029,     1011,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      1228,     1029,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2012,     1031,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2012,     1031,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1031,     1032,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      5012,     1032,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      5012,     1032,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      4009,     1033,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1014,     1034,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1014,     1034,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1033,     1034,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1033,     1034,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1033,     1034,     1035,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
         0,     1035,        0, 183,0, 0, LCY for a node differs from its neighbours
      1039,     1035,     1034, 124,0, 0, A nearside turn is all-green but not coded as a filter F
      7039,     1039,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     1040,        0, 186,0, 0, Intergreen equals zero but, eg N-S ends and E-W starts
      2006,     1040,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2006,     1040,     4008, 124,0, 0, A nearside turn is all-green but not coded as a filter F
      1024,     1042,     7039,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
         0,     1045,        0, 126,0, 0, Total intergreen stage times equal zero
      1040,     1045,     1047, 124,0, 0, A nearside turn is all-green but not coded as a filter F
      7100,     1047,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
         0,     1048,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
      2015,     1051,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5001,     1051,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1053,     1052,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1052,     1053,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1049,     1055,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1049,     1055,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     1059,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     1059,        0,  82,0, 0, Cycle time is very high - > 999 Seconds
         0,     1059,        0, 183,0, 0, LCY for a node differs from its neighbours
      2795,     1061,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2795,     1061,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      1062,     1063,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1062,     1063,     1066,  53,0, 0, Two priority turns share the same exit; should one give way?
      1064,     1063,     1066,  53,0, 0, Two priority turns share the same exit; should one give way?
         0,     1064,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     1064,        0,  19,0, 0, Total stage plus intergreen times not equal input cycle time
         0,     1066,        0, 183,0, 0, LCY for a node differs from its neighbours
      1063,     1066,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     1067,        0,  84,0, 0, Redundant intergreen stage time - all turns continuous green
      1072,     1071,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      5006,     1071,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1028,     1072,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1028,     1072,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1102,     1081,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     1086,        0,   6,0, 0, A priority junction has no minor but multiple major arms
      1118,     1086,     3001,  53,0, 0, Two priority turns share the same exit; should one give way?
      1224,     1086,     3001,  53,0, 0, Two priority turns share the same exit; should one give way?
      7500,     1087,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     1088,        0, 183,0, 0, LCY for a node differs from its neighbours
      7501,     1088,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7501,     1088,     7006, 128,0, 0, Zero sat flow for a turn which is green during a stage
      1088,     1089,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1088,     1089,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
         0,     1090,        0,  19,0, 0, Total stage plus intergreen times not equal input cycle time
         0,     1090,        0, 183,0, 0, LCY for a node differs from its neighbours
      7007,     1090,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2065,     1092,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      7035,     1092,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7035,     1092,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1026,     1094,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      1026,     1094,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1026,     1094,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7009,     1094,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1129,     1095,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      4002,     1095,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1095,     1096,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1095,     1096,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      6004,     1096,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1075,     1098,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1137,     1098,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      5013,     1098,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1081,     1102,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1081,     1102,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1138,     1102,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1138,     1102,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     1107,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      2026,     1107,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1108,     1109,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     1117,        0, 183,0, 0, LCY for a node differs from its neighbours
      1118,     1117,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5015,     1119,     1118,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
      2204,     1120,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2122,     1127,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2122,     1127,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2122,     1127,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2122,     1127,     7502,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      7502,     1127,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      7502,     1127,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2797,     1129,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2797,     1129,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1096,     1132,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1096,     1132,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1096,     1132,     2001,  53,0, 0, Two priority turns share the same exit; should one give way?
      1133,     1132,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1133,     1132,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1133,     1132,     2001,  53,0, 0, Two priority turns share the same exit; should one give way?
      2001,     1132,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      4000,     1132,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1132,     1133,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1132,     1133,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1142,     1133,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1142,     1133,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5006,     1133,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     1135,        0, 183,0, 0, LCY for a node differs from its neighbours
      1066,     1135,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1067,     1135,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1136,     1135,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1136,     1135,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1136,     1135,     1067,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      1135,     1136,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1102,     1138,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1140,     1139,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1140,     1139,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1146,     1139,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1133,     1142,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1139,     1146,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1147,     1146,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1147,     1146,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1120,     1148,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1146,     1148,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1146,     1148,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1149,     1148,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1149,     1148,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1148,     1149,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2506,     1206,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2737,     1206,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1221,     1208,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1338,     1208,        0,  54,0, 0, Duplicate and different capacity indices
      1343,     1211,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2067,     1211,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2067,     1211,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2068,     1211,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2068,     1211,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2068,     1211,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1006,     1214,     1215,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
      1214,     1215,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1203,     1216,     1217,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
      1236,     1219,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1237,     1220,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1237,     1220,        0, 162,0, 0, Multiple turns sharing multiple lanes: leads to weaving
      1208,     1221,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1089,     1224,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      1227,     1226,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1226,     1227,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     1228,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
      1209,     1230,        0,  32,0, 0, Simulation link distances and/or times differ in reverse
      1221,     1231,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1234,     1231,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1220,     1233,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1231,     1235,        0, 162,0, 0, Multiple turns sharing multiple lanes: leads to weaving
      1236,     1237,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5032,     1303,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1326,     1305,        0,  54,0, 0, Duplicate and different capacity indices
      2750,     1305,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2854,     1305,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     1308,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      2106,     1308,        0,  54,0, 0, Duplicate and different capacity indices
      2106,     1308,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
         0,     1309,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      1347,     1309,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2770,     1309,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5046,     1309,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5046,     1309,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5104,     1311,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1315,     1312,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5103,     1312,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1312,     1315,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2787,     1318,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1320,     1319,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1321,     1319,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1352,     1319,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1319,     1320,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1204,     1321,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1319,     1321,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1350,     1321,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1350,     1321,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2791,     1321,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1320,     1322,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1320,     1322,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1326,     1322,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1326,     1322,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2612,     1322,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2612,     1322,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2692,     1322,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2692,     1322,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2692,     1322,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2793,     1322,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2793,     1322,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2793,     1322,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2793,     1322,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      5026,     1322,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5026,     1322,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      7503,     1322,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7503,     1322,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1324,     1323,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2853,     1323,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2853,     1323,     2650,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      5034,     1323,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5034,     1323,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1323,     1324,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1325,     1324,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1325,     1324,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1327,     1324,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1327,     1324,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1350,     1324,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1350,     1324,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2654,     1324,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2654,     1324,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2655,     1324,     2655,  73,0, 0, Bus route with U-turns at non-simulation nodesS
      2735,     1324,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1324,     1325,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1324,     1325,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2610,     1325,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2610,     1325,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2713,     1325,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2713,     1325,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2760,     1325,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      7503,     1325,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      7503,     1325,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7503,     1325,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1305,     1326,        0,  54,0, 0, Duplicate and different capacity indices
      1305,     1326,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1322,     1326,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1322,     1326,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2610,     1326,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2610,     1326,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2745,     1326,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2745,     1326,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5025,     1326,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5025,     1326,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1324,     1327,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1324,     1327,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1329,     1327,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2654,     1327,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2657,     1327,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2657,     1327,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2657,     1327,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2723,     1328,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2877,     1328,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2877,     1328,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2877,     1328,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      5065,     1328,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5065,     1328,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1327,     1329,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2507,     1329,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2705,     1329,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2705,     1329,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2711,     1329,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2858,     1329,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2858,     1329,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1331,     1330,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1331,     1330,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1332,     1330,        0,  54,0, 0, Duplicate and different capacity indices
      2658,     1330,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2686,     1330,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1330,     1331,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1330,     1331,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1332,     1331,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2130,     1331,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2658,     1331,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2658,     1331,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2800,     1331,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2800,     1331,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1330,     1332,        0,  54,0, 0, Duplicate and different capacity indices
      1330,     1332,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1330,     1332,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1331,     1332,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1333,     1332,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2668,     1332,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2668,     1332,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2686,     1332,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2686,     1332,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2800,     1332,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2800,     1332,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1307,     1333,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1332,     1333,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1334,     1333,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2659,     1333,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2665,     1333,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1333,     1334,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1336,     1334,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2615,     1334,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2615,     1334,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2667,     1334,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2667,     1334,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1334,     1336,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1334,     1336,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1334,     1336,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2142,     1336,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2686,     1336,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2686,     1336,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      6006,     1336,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      6006,     1336,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1338,     1337,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1338,     1337,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2142,     1337,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2602,     1337,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2602,     1337,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2687,     1337,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2687,     1337,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2687,     1337,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2703,     1337,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2706,     1337,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2882,     1337,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
         0,     1338,        0,  15,0, 0, Maximum roundabout turn sat flow exceeds circulation sat flo
         0,     1338,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      1208,     1338,        0,  54,0, 0, Duplicate and different capacity indices
      1337,     1338,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1337,     1338,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1339,     1338,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1340,     1338,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1340,     1338,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2603,     1338,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2689,     1338,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1338,     1339,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2602,     1339,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2602,     1339,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5023,     1339,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5023,     1339,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1338,     1340,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1338,     1340,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1345,     1340,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1345,     1340,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2603,     1340,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2603,     1340,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2603,     1340,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      5012,     1340,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5012,     1340,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1346,     1341,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1347,     1341,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1211,     1343,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1211,     1343,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1342,     1343,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2767,     1344,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1340,     1345,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1346,     1345,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      5012,     1345,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5012,     1345,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5021,     1345,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5021,     1345,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1341,     1346,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1347,     1346,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2773,     1346,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2773,     1346,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2773,     1346,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2896,     1346,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1309,     1347,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1341,     1347,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1346,     1347,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2768,     1347,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2773,     1347,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2773,     1347,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      5030,     1347,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5033,     1347,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5033,     1347,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5039,     1348,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      6140,     1348,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5036,     1349,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1324,     1350,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1324,     1350,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2653,     1350,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1319,     1352,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1132,     2001,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      6004,     2001,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      6004,     2001,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      4014,     2006,     1040,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
      2008,     2007,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1067,     2008,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2007,     2008,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2007,     2008,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1006,     2013,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2000,     2013,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2010,     2013,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1004,     2014,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1005,     2014,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     2023,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      2025,     2023,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2023,     2025,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1107,     2026,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1107,     2026,     1107,  73,0, 0, Bus route with U-turns at non-simulation nodesS
      2997,     2026,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2075,     2031,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2075,     2031,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2075,     2031,     1019,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      1021,     2032,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2033,     2032,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2032,     2033,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2601,     2034,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2601,     2034,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2601,     2034,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2609,     2034,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2609,     2034,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2205,     2035,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2605,     2035,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      4007,     2035,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1073,     2037,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1073,     2037,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2036,     2037,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1059,     2042,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1059,     2042,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2043,     2042,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2045,     2044,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2045,     2044,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2045,     2044,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      3000,     2044,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2044,     2045,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2050,        0, 183,0, 0, LCY for a node differs from its neighbours
      2069,     2050,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2149,     2050,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2149,     2050,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2149,     2050,     2069,  79,0, 0, An X-turn at signals is only in unopposed stages - no TAX
      2149,     2050,     2069, 111,0, 0, No opposing turns found for a turn with a Priority Marker
      5008,     2050,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5008,     2050,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1083,     2051,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2052,     2051,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      5013,     2051,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1092,     2065,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1092,     2065,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2066,     2065,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2066,     2065,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2066,     2065,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2067,     2065,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2065,     2066,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1211,     2068,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2050,     2069,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2991,     2070,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      6001,     2070,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2072,     2071,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2072,     2071,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2072,     2071,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      7050,     2071,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2071,     2072,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2074,     2073,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2074,     2073,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7061,     2073,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7061,     2073,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2073,     2074,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2167,     2100,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2749,     2101,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5129,     2101,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2160,     2102,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2166,     2102,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5121,     2102,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2116,     2103,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2118,     2103,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2144,     2103,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2162,     2103,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5003,     2103,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5130,     2103,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2130,     2104,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2130,     2104,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5019,     2104,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2109,     2105,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2754,     2105,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2106,        0,  15,0, 0, Maximum roundabout turn sat flow exceeds circulation sat flo
      1308,     2106,        0,  54,0, 0, Duplicate and different capacity indices
      1308,     2106,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2613,     2106,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2613,     2106,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5004,     2106,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5004,     2106,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5006,     2106,        0,  30,0, 0, Calculated speed outside the expected min/max range
      5006,     2106,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5006,     2106,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5028,     2106,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5028,     2106,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5029,     2106,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2108,     2107,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2109,     2107,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2786,     2107,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5008,     2107,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5009,     2107,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2107,     2108,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2136,     2108,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5018,     2108,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5052,     2108,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      9005,     2108,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      9007,     2108,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2105,     2109,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2107,     2109,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2131,     2109,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2168,     2109,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5002,     2109,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
         0,     2110,        0,  52,0, 0, External simulation node with 2 arms - unusual
      2786,     2110,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5022,     2110,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2685,     2111,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5133,     2111,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2113,     2112,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2785,     2112,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2849,     2112,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5069,     2112,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2112,     2113,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2136,     2113,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2848,     2113,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2114,        0,  52,0, 0, External simulation node with 2 arms - unusual
      2824,     2114,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      5045,     2114,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2103,     2116,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2829,     2116,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2831,     2116,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5126,     2116,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2103,     2118,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2834,     2118,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5132,     2118,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2122,     2121,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1127,     2122,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2121,     2122,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2121,     2122,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1331,     2130,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2104,     2130,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2104,     2130,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2131,     2130,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2611,     2130,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2660,     2130,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2690,     2130,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2690,     2130,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      5025,     2130,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5025,     2130,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1307,     2131,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2109,     2131,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2130,     2131,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2674,     2131,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5010,     2131,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5010,     2131,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2785,     2132,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2849,     2132,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5056,     2132,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2138,     2133,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2140,     2133,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5101,     2133,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2138,     2134,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2849,     2134,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2136,     2135,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2137,     2135,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2108,     2136,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2113,     2136,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2135,     2136,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2141,     2136,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5051,     2136,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5054,     2136,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      9006,     2136,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2135,     2137,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5047,     2137,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5049,     2137,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      9001,     2137,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      9002,     2137,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      9003,     2137,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      9004,     2137,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2133,     2138,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2134,     2138,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5055,     2139,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2133,     2140,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5100,     2140,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2136,     2141,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5048,     2141,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5050,     2141,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5020,     2143,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2103,     2144,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5116,     2144,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5131,     2144,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
         0,     2146,        0, 183,0, 0, LCY for a node differs from its neighbours
      1018,     2147,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1018,     2147,     2150, 148,0, 0, The rules for green during intergreen differ in 10.6
      2050,     2149,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2071,     2149,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
         0,     2150,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
      2102,     2160,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2164,     2161,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2103,     2162,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2163,     2162,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2162,     2163,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5124,     2163,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2161,     2164,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2165,     2164,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2164,     2165,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2756,     2165,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2102,     2166,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2100,     2167,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2828,     2167,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2109,     2168,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5068,     2168,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5139,     2168,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      9008,     2168,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      9009,     2168,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2022,     2200,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2201,     2200,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2201,     2200,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2201,     2200,     2023,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      2200,     2201,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      4007,     2202,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2204,        0, 113,0, 0, Input simulation arms not in (counter-)clockwise order
      1120,     2204,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1120,     2204,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2600,     2204,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2607,     2204,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2607,     2204,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2035,     2205,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2607,     2205,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1329,     2507,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2604,     2507,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2604,     2507,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2710,     2507,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2810,     2507,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      5067,     2507,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2204,     2600,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2204,     2600,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2601,     2600,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2601,     2600,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2601,     2600,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2034,     2601,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2600,     2601,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1337,     2602,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1337,     2602,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1339,     2602,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1339,     2602,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2714,     2602,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2714,     2602,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1338,     2603,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1340,     2603,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1340,     2603,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2689,     2603,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2689,     2603,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2689,     2603,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2507,     2604,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2507,     2604,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2852,     2604,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2852,     2604,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2853,     2604,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2853,     2604,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2853,     2604,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2600,     2605,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2606,     2605,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2606,     2605,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2204,     2607,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2204,     2607,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2205,     2607,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2205,     2607,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2205,     2607,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2608,     2607,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2608,     2607,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2607,     2608,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1325,     2610,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1325,     2610,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1326,     2610,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1326,     2610,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2656,     2610,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2713,     2610,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2762,     2610,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2762,     2610,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
         0,     2611,        0,  52,0, 0, External simulation node with 2 arms - unusual
      2130,     2611,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1322,     2612,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1322,     2612,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2692,     2612,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2106,     2613,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2106,     2613,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2781,     2613,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2817,     2613,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2651,     2650,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2651,     2650,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2650,     2651,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2652,     2651,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2651,     2652,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2651,     2652,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2653,     2652,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2653,     2652,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1350,     2653,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1327,     2654,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1327,     2654,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2760,     2654,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2761,     2655,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2761,     2655,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2761,     2655,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2610,     2656,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2745,     2656,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2793,     2656,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2793,     2656,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1327,     2657,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1327,     2657,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1327,     2657,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2658,     2657,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2658,     2657,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2856,     2657,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2856,     2657,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1330,     2658,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1331,     2658,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1331,     2658,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1331,     2658,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2657,     2658,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2657,     2658,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1333,     2659,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1333,     2659,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2759,     2659,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2130,     2660,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2130,     2660,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2659,     2660,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2659,     2660,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2662,     2660,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2662,     2660,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2739,     2660,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2739,     2660,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2741,     2661,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2859,     2661,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2881,     2661,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2881,     2661,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2881,     2661,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2660,     2662,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2660,     2662,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2660,     2662,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2663,     2662,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2663,     2662,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2664,     2662,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2664,     2663,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2664,     2663,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2665,     2663,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2662,     2664,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2663,     2664,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2666,     2664,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2666,     2664,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1333,     2665,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2663,     2665,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2667,     2665,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2673,     2666,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2665,     2667,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2669,     2667,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1332,     2668,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2667,     2669,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2670,     2669,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2671,     2669,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2671,     2669,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2671,     2669,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2669,     2670,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2669,     2670,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2669,     2670,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2804,     2670,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2669,     2671,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2669,     2671,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2669,     2671,     2672,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      2131,     2672,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2671,     2672,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2775,     2672,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2775,     2672,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2775,     2672,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2130,     2673,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2130,     2673,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2666,     2673,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2666,     2673,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2666,     2673,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2816,     2673,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     2674,        0, 183,0, 0, LCY for a node differs from its neighbours
      2131,     2674,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2131,     2674,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2678,     2674,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2775,     2674,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2775,     2674,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2775,     2674,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2775,     2674,        0, 152,0, 0, A single lane arm at signals which includes an X-marked turn
         0,     2675,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      2678,     2675,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2680,     2675,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2680,     2675,        0,  54,0, 0, Duplicate and different capacity indices
      2683,     2676,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2758,     2676,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2860,     2676,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2860,     2676,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2765,     2677,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2804,     2677,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2674,     2678,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2675,     2678,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2675,     2680,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2685,     2681,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2814,     2682,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2815,     2682,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5137,     2682,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2676,     2683,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2817,     2683,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2817,     2683,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2818,     2683,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2818,     2683,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2818,     2683,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2777,     2684,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2111,     2685,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2681,     2685,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2754,     2685,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5016,     2685,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1330,     2686,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1332,     2686,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1336,     2686,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1336,     2686,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1336,     2686,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1337,     2687,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1337,     2687,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2714,     2687,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2714,     2687,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2714,     2687,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2613,     2688,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2717,     2688,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2717,     2688,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2778,     2688,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1338,     2689,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2603,     2689,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2603,     2689,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2603,     2689,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2703,     2689,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2703,     2689,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2130,     2690,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2130,     2690,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2682,     2690,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2855,     2690,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2611,     2691,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2864,     2691,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2881,     2691,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2881,     2691,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2881,     2691,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1322,     2692,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1322,     2692,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1322,     2692,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2612,     2692,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2612,     2692,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2748,     2692,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2748,     2692,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2749,     2693,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2812,     2693,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1339,     2696,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2714,     2696,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2822,     2697,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2822,     2697,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2697,     2698,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2699,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      2704,     2699,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      6006,     2699,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2699,     2700,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2704,     2700,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2704,     2700,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2704,     2700,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2705,     2700,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2705,     2700,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2705,     2700,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2850,     2700,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2850,     2700,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2850,     2700,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2706,     2701,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2721,     2701,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2721,     2701,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2806,     2701,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1337,     2703,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1337,     2703,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2689,     2703,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2719,     2703,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2699,     2704,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2700,     2704,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2700,     2704,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2700,     2704,     2699,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      2721,     2704,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2721,     2704,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2721,     2704,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1329,     2705,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2700,     2705,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2700,     2705,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2701,     2706,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2701,     2706,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2880,     2706,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2880,     2706,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     2708,        0,  15,0, 0, Maximum roundabout turn sat flow exceeds circulation sat flo
         0,     2708,        0, 138,0, 0, Saturation flows differ widely between roundabout arms
      5028,     2708,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5028,     2708,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5030,     2708,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      5030,     2708,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2506,     2709,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2733,     2710,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1329,     2711,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2733,     2711,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2733,     2711,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2734,     2711,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2734,     2711,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1325,     2713,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2610,     2713,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2602,     2714,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2602,     2714,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2687,     2714,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2696,     2714,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2696,     2714,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2687,     2715,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2687,     2715,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2716,     2715,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2780,     2715,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2715,     2716,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2718,     2717,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2718,     2717,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2780,     2717,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2780,     2717,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2717,     2718,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2703,     2719,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2701,     2721,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2701,     2721,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2704,     2721,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2722,     2721,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2722,     2721,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2721,     2722,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2724,     2723,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2852,     2723,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2723,     2724,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2727,     2726,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2727,     2726,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2810,     2726,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2810,     2726,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2726,     2727,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2877,     2728,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2877,     2728,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2799,     2729,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2729,     2731,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2729,     2731,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2732,     2731,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2732,     2731,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2731,     2732,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2710,     2733,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2731,     2733,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2711,     2734,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2652,     2735,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2736,     2735,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2736,     2735,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2736,     2735,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2735,     2736,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      6006,     2738,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2740,     2739,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2741,     2739,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2741,     2739,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2741,     2739,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2739,     2741,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2739,     2741,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2739,     2741,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2739,     2741,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2739,     2741,        0, 157,0, 0, The mid-link capacity is either >> or << stop-line sat flow
      2742,     2741,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2742,     2741,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2742,     2741,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2741,     2742,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2741,     2742,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1326,     2745,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1326,     2745,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1326,     2745,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2656,     2745,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2746,     2745,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2746,     2745,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2745,     2746,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2745,     2746,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2747,     2746,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2748,     2746,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2748,     2746,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2751,     2746,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2751,     2746,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2746,     2747,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2749,     2747,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2749,     2747,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2749,     2747,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2692,     2748,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2746,     2748,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2101,     2749,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2693,     2749,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2747,     2749,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1305,     2750,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2746,     2751,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2678,     2752,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2678,     2752,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2753,     2752,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2753,     2752,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2758,     2752,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2758,     2752,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2752,     2753,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2105,     2754,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2685,     2754,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5015,     2755,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2165,     2756,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5125,     2756,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5128,     2757,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2752,     2758,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1325,     2760,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2654,     2760,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2655,     2761,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2610,     2762,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2802,     2762,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1336,     2764,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1336,     2764,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2765,     2764,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2850,     2764,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2850,     2764,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2677,     2765,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2677,     2765,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2766,     2765,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2766,     2765,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2765,     2766,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1344,     2767,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1341,     2768,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1347,     2768,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2769,     2768,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2768,     2769,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1309,     2770,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2772,     2771,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2772,     2771,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2784,     2771,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2784,     2771,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2784,     2771,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2799,     2771,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2771,     2772,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1346,     2773,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1346,     2773,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1346,     2773,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1347,     2773,        0,  32,0, 0, Simulation link distances and/or times differ in reverse
      2774,     2773,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2774,     2773,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2773,     2774,        0,  32,0, 0, Simulation link distances and/or times differ in reverse
      2773,     2774,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2672,     2775,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2672,     2775,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2672,     2775,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2672,     2775,        0, 157,0, 0, The mid-link capacity is either >> or << stop-line sat flow
      2674,     2775,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2776,     2775,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2776,     2775,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2776,     2775,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2775,     2776,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2775,     2776,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2684,     2777,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5006,     2777,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2106,     2778,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2688,     2778,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2779,     2778,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2779,     2778,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2779,        0,  28,0, 0, A zone CC goes to an external sim link joint with buffer
      2778,     2779,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2715,     2780,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2717,     2780,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2717,     2780,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2781,     2780,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2781,     2780,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2613,     2781,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2780,     2781,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2783,     2782,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2784,     2782,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2784,     2782,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2784,     2782,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2782,     2783,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2771,     2784,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2771,     2784,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2771,     2784,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2782,     2784,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2112,     2785,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2132,     2785,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5053,     2785,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2107,     2786,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2110,     2786,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2891,     2786,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5007,     2786,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1318,     2787,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5035,     2787,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7033,     2788,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1005,     2789,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1005,     2789,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2790,     2789,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2790,     2789,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2789,     2790,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1321,     2791,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1321,     2791,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2792,     2791,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2792,     2791,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2792,     2791,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7503,     2791,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2791,     2792,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1322,     2793,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1322,     2793,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      1322,     2793,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1322,     2793,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2794,     2793,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2794,     2793,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2794,     2793,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2793,     2794,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2793,     2794,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2796,     2795,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5004,     2795,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      2795,     2796,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1128,     2797,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1128,     2797,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2798,     2797,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2798,     2797,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2797,     2798,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2729,     2799,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2729,     2799,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2730,     2799,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2771,     2799,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1331,     2800,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1332,     2800,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1332,     2800,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1332,     2800,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2801,     2800,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2801,     2800,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2800,     2801,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2762,     2802,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2762,     2802,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2803,     2802,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2803,     2802,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2802,     2803,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2677,     2804,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2677,     2804,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2805,     2804,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2805,     2804,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2804,     2805,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2719,     2806,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2719,     2806,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2807,     2806,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2602,     2808,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2602,     2808,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2507,     2810,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2811,     2810,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2811,     2810,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2811,     2810,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2810,     2811,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2693,     2812,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2813,     2812,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2813,     2812,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2812,     2813,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2682,     2814,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2682,     2815,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2690,     2815,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2816,     2815,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2131,     2816,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2131,     2816,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2673,     2816,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2815,     2816,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2613,     2817,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2846,     2817,     2613,  14,0, 0, Roundabout turn sat flow less than circulation sat flow
      2683,     2818,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2683,     2818,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2777,     2818,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2777,     2818,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     2820,        0, 183,0, 0, LCY for a node differs from its neighbours
      1089,     2820,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2698,     2821,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2697,     2822,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2697,     2822,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2114,     2824,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2114,     2824,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2114,     2824,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2114,     2824,        0, 157,0, 0, The mid-link capacity is either >> or << stop-line sat flow
      2825,     2824,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2825,     2824,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2825,     2824,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2824,     2825,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2824,     2825,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
         0,     2826,        0,  15,0, 0, Maximum roundabout turn sat flow exceeds circulation sat flo
      2827,     2826,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2894,     2826,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2894,     2826,     2893, 168,0, 0, A roundabout turn is banned but other turns use that exit
      2826,     2827,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2826,     2827,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2826,     2827,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2836,     2827,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2837,     2827,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2837,     2827,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2837,     2827,     2826,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      2167,     2828,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2116,     2829,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2832,     2830,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2116,     2831,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2830,     2832,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2118,     2834,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2106,     2836,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2106,     2836,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2827,     2836,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2827,     2836,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2837,     2836,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2837,     2836,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
      2837,     2836,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2837,     2836,     2827,  98,0, 0, Possible opportunity for a Clear Exit Priority Modifier?
      2827,     2837,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2836,     2837,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2836,     2837,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2817,     2846,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2817,     2846,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2892,     2846,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2892,     2846,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2848,     2847,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2849,     2847,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5102,     2847,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2113,     2848,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2847,     2848,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2849,     2848,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5102,     2848,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2112,     2849,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2132,     2849,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2134,     2849,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2847,     2849,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2848,     2849,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2700,     2850,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2604,     2852,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1323,     2853,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2604,     2853,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2604,     2853,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2994,     2853,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1305,     2854,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2690,     2855,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2861,     2855,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2657,     2856,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2657,     2856,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2857,     2856,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1327,     2857,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2655,     2857,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2655,     2857,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2856,     2857,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2856,     2857,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1329,     2858,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2676,     2860,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2895,     2860,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2855,     2861,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2691,     2864,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2877,        0, 183,0, 0, LCY for a node differs from its neighbours
      1328,     2877,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2728,     2877,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2661,     2881,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2691,     2881,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1337,     2882,        0,  24,0, 0, Input link time/speed out of range from speed-flow record
      1337,     2882,        0,  32,0, 0, Simulation link distances and/or times differ in reverse
      2786,     2891,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2892,     2891,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2846,     2892,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2891,     2892,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2826,     2893,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2824,     2894,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      2893,     2894,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     2895,        0,  19,0, 0, Total stage plus intergreen times not equal input cycle time
      2860,     2895,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1346,     2896,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2991,     2990,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2070,     2991,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2990,     2991,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1020,     2992,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2995,     2993,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2993,     2995,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2993,     2995,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2996,     2995,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5019,     2995,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      5019,     2995,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5019,     2995,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2995,     2996,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2997,     2996,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2026,     2997,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2996,     2997,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2998,     2997,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2997,     2998,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      3004,     3001,     1086, 160,0, 0, Merge turns enter a link which has significantly fewer lanes
      6006,     3002,     3006,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
      3006,     3003,     1233, 160,0, 0, Merge turns enter a link which has significantly fewer lanes
      3024,     3004,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      3006,     3007,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      3000,     3008,     3009,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
      3007,     3008,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      3008,     3009,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      3008,     3009,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      3000,     3011,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      3000,     3011,     3016,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
         0,     3016,        0,  15,0, 0, Maximum roundabout turn sat flow exceeds circulation sat flo
      3019,     3016,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7059,     3016,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      3016,     3019,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      3009,     3024,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      7049,     4000,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
         0,     4001,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     4002,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     4002,        0, 183,0, 0, LCY for a node differs from its neighbours
      2122,     4003,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1002,     4007,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1002,     4007,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2035,     4007,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2035,     4007,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2202,     4007,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2202,     4007,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2202,     4007,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7505,     4007,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1039,     4009,        0, 157,0, 0, The mid-link capacity is either >> or << stop-line sat flow
      4011,     4010,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      4011,     4010,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7038,     4010,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7038,     4010,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7038,     4010,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      4010,     4011,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2150,     4012,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2150,     4012,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      4013,     4012,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1030,     5001,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1030,     5001,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1051,     5001,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5002,     5001,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2109,     5002,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2103,     5003,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1052,     5004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1052,     5004,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2106,     5004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2106,     5004,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2106,     5006,        0,  30,0, 0, Calculated speed outside the expected min/max range
      2106,     5006,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2106,     5006,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2777,     5006,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2050,     5008,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2050,     5008,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2050,     5008,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2107,     5008,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5009,     5008,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      6001,     5008,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2107,     5009,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5008,     5009,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1210,     5010,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1210,     5010,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2131,     5010,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      2131,     5010,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5011,     5010,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      5011,     5010,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5010,     5011,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1032,     5012,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1340,     5012,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1345,     5012,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1312,     5013,        0,  30,0, 0, Calculated speed outside the expected min/max range
      2755,     5015,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2685,     5016,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      1021,     5018,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2108,     5018,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5019,     5018,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2104,     5019,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2995,     5019,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      5018,     5019,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2070,     6001,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      5008,     6001,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      5008,     6001,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7051,     6001,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1096,     6004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1096,     6004,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1096,     6004,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2001,     6004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      6005,     6004,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      6005,     6004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      6004,     6005,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1336,     6006,        0,  49,0, 0, A buffer link has both A and B-node in the simulation
      1336,     6006,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      2699,     6006,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2699,     6006,        0, 189,0, 0, Disagreement between data read as fixed columns and free/CSV
      2738,     6006,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2738,     6006,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      3002,     6006,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      3002,     6006,        0, 189,0, 0, Disagreement between data read as fixed columns and free/CSV
      7110,     7001,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7003,     7002,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      7004,     7002,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7004,     7002,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7054,     7002,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      7002,     7004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7051,     7004,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1094,     7009,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7026,     7017,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      7017,     7018,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      7020,     7021,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      7020,     7021,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7022,     7023,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
         0,     7024,        0, 183,0, 0, LCY for a node differs from its neighbours
      7024,     7025,        0,  65,0, 0, Low (chain) stacking capacity per lane (1.0 < 3.0 PCU)
      7024,     7025,        0, 162,0, 0, Multiple turns sharing multiple lanes: leads to weaving
         0,     7026,        0, 183,0, 0, LCY for a node differs from its neighbours
      7029,     7028,     1116,  68,0, 0, A priority marker G looks suspiciously like a merge! (M)
         0,     7029,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7029,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7030,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7030,        0, 183,0, 0, LCY for a node differs from its neighbours
      1226,     7033,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      2788,     7033,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      2788,     7033,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7043,     7033,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     7038,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7038,        0, 183,0, 0, LCY for a node differs from its neighbours
      4010,     7038,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     7039,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7039,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7040,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7040,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7041,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7041,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7042,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7043,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7043,        0, 183,0, 0, LCY for a node differs from its neighbours
      7033,     7043,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     7044,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7045,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7045,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7047,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7047,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7048,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7048,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7049,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7049,        0, 183,0, 0, LCY for a node differs from its neighbours
         0,     7050,        0,  16,0, 0, Rather long intergreen time for a stage (> 20 seconds)
         0,     7050,        0, 183,0, 0, LCY for a node differs from its neighbours
      7004,     7051,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
         0,     7052,        0,  15,0, 0, Maximum roundabout turn sat flow exceeds circulation sat flo
      7054,     7052,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7052,     7054,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7052,     7054,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7055,     7054,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      7055,     7054,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
         0,     7057,        0,  15,0, 0, Maximum roundabout turn sat flow exceeds circulation sat flo
      7058,     7057,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      7058,     7057,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7057,     7058,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7059,     7058,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7059,     7058,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7060,     7058,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      7060,     7058,        0,  51,0, 0, The saturation flow per lane is greater than MAXLSF
         0,     7059,        0, 183,0, 0, LCY for a node differs from its neighbours
      3016,     7059,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7058,     7059,        0,  23,0, 0, Total upstream sat flow inconsistent with lanes downstream
      7057,     7061,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      7057,     7061,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      7062,     7061,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1047,     7100,        0,  32,0, 0, Simulation link distances and/or times differ in reverse
      1047,     7100,        0, 136,0, 0, Suspicious link distance compared to crow-fly distance
      7001,     7110,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1087,     7501,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1325,     7503,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
      1325,     7503,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      1325,     7503,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      2791,     7503,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      2791,     7503,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1003,     7506,        0, 135,0, 0, 2+ give-way turns in a single lane: Major arm priority jcn.
      1003,     7506,        0, 137,0, 0, Turn saturation flows per lane differ widely. See 6.4.6.3
      1004,     7506,        0,  33,0, 0, Suspicious link distance - Input values differ markedly
      7507,     7506,        0,  12,0, 0, More than one give-way turn sharing a single lane; Priority
